config/routes.rb
Jamdancedaddymovemomma::Application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  
  resources :videos
  root :to => 'home#index'

  get "home/single"
  get "home/initvideos"
  get "home/initvinevideos"
  get "home/whopass"
  post "home/whopass"
  post "home/index"

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :description, :name, :thumbnail_image_url, :url, :view_count, :video_id

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "blank"
  

  # GET /videos
  # GET /videos.json
  def index
    @leftsidebgcolor = "orange"
    @rightsidebgcolor = "darkblue"
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1/edit
  def edit
    @leftsidebgcolor = "orange"
    @rightsidebgcolor = "darkblue"
    @video = Video.find(params[:id])
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	protect_from_forgery except: :index
	include HomeHelper
	def single

		@leftsidebgcolor = "orange"
		@rightsidebgcolor = "darkblue"
		@canvascolor = "#3072c4"


		offset = rand(Video.count)

		@video = Video.first(:offset => offset)

	end

	def index
		
		redirect_to 'http://www.jamaudio.com/danceoff?'


		
		
		require 'date'
		
		@timestamp = DateTime.now.strftime('%Q')


		@leftsidebgcolor = "blue"
		@rightsidebgcolor = "pink"
		@canvascolor = "#db438f"



		offset = rand(Video.count)
		offset2 = rand(Video.count)

		while Video.first(:offset => offset).ignored == true
			offset = rand(Video.count)
		end

		while offset == offset2 
			offset2 = rand(Video.count)
		end

		while Video.first(:offset => offset2).ignored == true || offset2 == offset
			offset2 = rand(Video.count)
		end

		@firstvideo = Video.first(:offset => offset)
		@secondvideo = Video.first(:offset => offset2)

		if params[:winner] != nil
			winner = Integer(params[:winner])

		    video = Video.find(winner)

		    video.view_count = video.view_count + 1
		    
		    video.save
       
		    redirect_to :back
	    end

	end

	def whopass
    end

	def initvideos
		
		@leftsidebgcolor = "blue"
		@rightsidebgcolor = "pink"
		@canvascolor = "#db438f"



		offset = rand(Video.count)
		offset2 = rand(Video.count)

		while Video.first(:offset => offset).ignored == true
			offset = rand(Video.count)
		end

		while offset == offset2 
			offset2 = rand(Video.count)
		end

		while Video.first(:offset => offset2).ignored == true || offset2 == offset
			offset2 = rand(Video.count)
		end

		@firstvideo = Video.first(:offset => offset)
		@secondvideo = Video.first(:offset => offset2)

		if params[:winner] != nil
			winner = Integer(params[:winner])

		    video = Video.find(winner)

		    video.view_count = video.view_count + 1
		    
		    video.save
       
		    redirect_to :back
	    end
	end

	def initvinevideos
		
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.from_omniauth(env["omniauth.auth"])
		session[:user_id] = user.id
		redirect_to root_url
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	def index
		
		redirect_to 'http://www.jamaudio.com/danceoff?'

		@leftsidebgcolor = "orange"
		@rightsidebgcolor = "pink"
		@canvascolor = "#db438f"

		if request.original_url.include? "pop"
			videos = Video.order("videos.view_count DESC")
		else
			videos = Video.order("videos.created_at DESC")
		end

		videos = videos.where(ignored: nil)

		@searchmode = false

		if params['search'] != nil
			videos = videos.where(name: params['search'])
			
			
			@searchmode = true

			if videos.count > 0
				@rightsidebgcolor = "darkblue"
				@canvascolor = "#3072c4"
			end

		end
		
		@videos = videos
		@searchparam = params['search']
	end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

	def InitInstagramVideos()
		require "net/https"
		require "uri"
		require 'json'

		begin
			uri = URI.parse("https://api.instagram.com/v1/tags/Jam25kentry/media/recent?access_token=201508105.1fb234f.23f267ecdf4d409980c2d4163a3e3b4e&max_tag_id=1402827536318607")
				http = Net::HTTP.new(uri.host, uri.port)
				http.use_ssl = true
				http.verify_mode = OpenSSL::SSL::VERIFY_NONE

				request = Net::HTTP::Get.new(uri.request_uri)

				response = http.request(request)
				puts response.body

				hash = JSON.parse response.body


				hash['data'].each do |child|

					if child['type'] == "video"
						unless Video.exists?(:video_id => child['id'])
							unless child['caption'].nil?
								video = Video.new

								video.name = child['user']['username']
								video.description =  child['caption']['text']
								video.url = child['videos']['standard_resolution']['url']
								video.thumbnail_image_url = child['images']['standard_resolution']['url']
								video.video_id = videoid = child['id']
								video.view_count = 0
								video.shareurl = child['link']

								video.save
							else
						  		next
							end
						end
					end
				end
		rescue => ex
		  logger.error ex.message
		end
		
	end


	def InitVineVideos()
		require "net/https"
		require "uri"
		require 'json'

		begin
		uri = URI.parse("https://api.vineapp.com/timelines/tags/Jam25kentry")
		http = Net::HTTP.new(uri.host, uri.port)
		http.use_ssl = true
		http.verify_mode = OpenSSL::SSL::VERIFY_NONE

		request = Net::HTTP::Get.new(uri.request_uri)

		response = http.request(request)
		puts response.body

		hash = JSON.parse response.body

		hash['data']['records'].each do |child|
			unless Video.exists?(:video_id => child['postId'].to_s)
				video = Video.new

				video.name = child['username']
				video.description = child['description']
				video.url = child['videoUrl']
				video.thumbnail_image_url = child['thumbnailUrl']
				video.video_id = child['postId'].to_s
				video.view_count = 0
				video.shareurl = child['shareUrl']

				video.save
			end
		end

		rescue => ex
		  logger.error ex.message
		end

	end


end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div style="height:600px">
  <table>
    <tr>
      <td>
        ID:
      </td>
      <td>
        <%= @video.id %>
      </td>
    </tr>
    <tr>
      <td>
        Name:
      </td>
      <td>
        <%= @video.name %>
      </td>
    </tr>
    <tr>
      <td>
        Description:
      </td>
      <td>
        <%= @video.description %>
      </td>
    </tr>
    <tr>
      <td>
        Video Url ID: 
      </td>
      <td>
        <%= @video.name %>
      </td>
    </tr>
    <tr>
      <td>
        Thumbnail Image Url:
      </td>
      <td>
        <%= @video.thumbnail_image_url %>
      </td>
    </tr>
    <tr>
      <td>
        Is Ignored:
      </td>
      <td>
        <%= @video.ignored %>
      </td>
    </tr>
    
  </table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/edit.html.erb
<div class="centerofpage" style=" background-color:white">
<%= render 'form' %>
<%= link_to 'Back', videos_path %>
</div>

app/views/admin/index.html.erb
<h1>Listing videos</h1>

<table style="width:400px">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @videos.each do |video| %>
  <tr>
    <td><%= video.name %></td>
    <td><%= link_to 'Edit', edit_admin_path(video) %></td>
  </tr>
<% end %>
</table>

app/views/admin/new.html.erb
<%= render 'videoheader' %>
<div class="container inner" style="width:500px!important">
	<%= render 'form' %>

	<%= link_to 'Back', videos_path %>
</div>

app/views/admin/show.html.erb
<%= render 'videoheader' %>
<div class="container inner" style="width:500px!important">
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>
</div>

app/views/home/index.html.erb
<div class="centerofpage" style="width:200px;top:295px;">

    <%= image_tag "or.png" %>
    <%= @video %>

    <a href="#data" class="fancybox" id="jasonlink" style="display:none"></a>

    <div id="jasonpopup" style="display:none">
        <div id="data" style="width:595px;height:420px;text-align:center">

            <div id="myElement"></div>

            <br/>
            <%= link_to("/auth/facebook", :id => "sign_in") do %>
                <%= image_tag "fblike.png"  %>
            <% end %>
        </div>
        
    </div>

    <a href="#data2" id="fbpopup_click" class="fancybox2" style="display:none"></a>

    <div id="fbpopup" style="display:none">
        <div id="data2" style="width:568px;height:346px">

            <%= image_tag "popupframe.png", :style => "position:absolute" %>

            <%= link_to("/auth/facebook", :id => "sign_in") do %>
                <%= image_tag "fblike.png", :style => "margin-left: 188px;margin-top: 100px;position:absolute" %>
            <% end %>
            
            <p style="margin-left: 133px;margin-top: 203px;position: absolute;">Make your selection count by liking Jam Audio.</p>
        </div>
    </div>
</div>


<% content_for :left_side do %>
    
    <div class="sliderholder" style="position:relative; margin-top:15px">
        <%= image_tag "slidepick_v2.png", :id => "viewcontrol", :style=>"position:relative", :class=>"slidepick" %>
        <div style="width: 75px;height: 54px;background-color: transparent;position: absolute;float: right;margin-top: -34px;cursor: pointer;margin-left: 133px;" onclick="ViewAll()"> </div>
    </div>

<% end %>

<% content_for :right_side do %>

    <%= image_tag "toprightbanner.png", :style => "float:right;z-index: 3;position: relative;margin-top:41px" %>

<% end %>


<div id="scroller" class="centerofpage" style="top:159px;">
    <div class="fltleft" style="margin-left:30px;height:494px">
        <p style="text-align:left;font-weight:bold;position:relative">
            <%= @firstvideo.name %>
        </p>
        <div class="videoframe bgcolororange shadowblue " style="position:relative">

            <div style="margin-left:15px;padding-top:15px" onmouseover="jwplayer('video_left').setMute(false);" onmouseout="jwplayer('video_left').setMute(true);">
                <div id="video_left"></div> 
            </div>

        </div>
        
        <div id="left_button_div" class="youpassbtn" onclick="formSubmit(<%= @firstvideo.id %>)"></div> 
    </div>
    <div class="fltright" style="margin-right:50px;">
        <p style="text-align:left;font-weight:bold">
            <%= @secondvideo.name %>
        </p>

        <div class="videoframe bgcolororange shadowpink" >

            <div style="margin-left:15px;padding-top:15px" onmouseover="jwplayer('video_right').setMute(false);" onmouseout="jwplayer('video_right').setMute(true);">
                <div id="video_right"></div> 
            </div>

        </div>

        <div id="right_button_div" class="youpassbtn" style="" onclick="formSubmit(<%= @secondvideo.id %>)"></div>   
    </div>
</div>

<img src="https://ad.amgdgt.com/ads/?t=ap&px=41949&rnd=<%= @timestamp %>" width="1" height="1" border="0"/>

<form id="whopass" accept-charset="UTF-8" action="/home/index" method="post" style="display:none">
    <input type="text" id="winner" name="winner" value="" />
</form>

<script>

    var test = '<%= current_user %>';
    var firstvideourl = '<%= @firstvideo.url %>';
    var secondvideourl = '<%= @secondvideo.url %>';
    var firstvideoimage = '<%= @firstvideo.thumbnail_image_url %>';
    var secondvideoimage = '<%= @secondvideo.thumbnail_image_url %>';




    $(document).ready(function() {

        jwplayer("video_left").setup({
                file: firstvideourl.replace("http", "https"),
                image: firstvideoimage,
                primary: "flash",
                width: 277,
                height: 277,
                autostart: false,
                repeat: true,
                mute: true,
            });

        jwplayer("video_right").setup({
                file: secondvideourl.replace("http", "https"),
                image: secondvideoimage,
                primary: "flash",
                width: 277,
                height: 277,
                autostart: false,
                repeat: true,
                mute: true,
            });

        $("a.fancybox3").fancybox({ 
            afterClose: function() {

                if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
            
                }
                else{
                    jwplayer('video_left').play();
                    jwplayer('video_right').play(); 
                }
            }
        });

        $("a.fancybox2").fancybox({
            tpl: {
              closeBtn: '<div title="Close" id="fb_close_button"></div>'
             }
        });

        $( "#viewcontrol" ).draggable({ 
            axis: "x", 
            grid: [ 162, 0 ], 
            containment: "parent",
            stop: function() 
            {
                var position = $('#viewcontrol').css('left');
                
                if (position == "80px")
                    location = "videos";
            }
        });
        $('#viewcontrol').css('left', '-82px');



    });

            

    $(window).bind("load", function() {

        if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
        
        }
        else
        {
            jwplayer('video_left').play();
            jwplayer('video_right').play(); 
        }
    });
    
    
    function formSubmit(x)
    {
        $('#winner').val(x);
        document.getElementById("whopass").submit();
    }

    function ViewAll()
    {
        location = "videos";
    }
</script>

app/views/home/initvideos.html.erb

<div class="centerofpage" style="width:200px;top:412px;overflow:hidden">

    <%= image_tag "or.png" %>
    <%= @video %>


    <a href="#data" class="fancybox" id="jasonlink" style="display:none"></a>

    <div id="jasonpopup" style="display:none">
        <div id="data" style="width:595px;height:420px;text-align:center">

            <div id="myElement"></div>

            <br/>
            <%= link_to("/auth/facebook", :id => "sign_in") do %>
                <%= image_tag "fblike.png"  %>
            <% end %>
        </div>
        
    </div>

    <a href="#data2" id="fbpopup_click" class="fancybox2" style="display:none"></a>

    <div id="fbpopup" style="display:none">
        <div id="data2" style="width:568px;height:346px">

            <%= image_tag "popupframe.png", :style => "position:absolute" %>

            <%= link_to("/auth/facebook", :id => "sign_in") do %>
                <%= image_tag "fblike.png", :style => "margin-left: 188px;margin-top: 100px;position:absolute" %>
            <% end %>

            
            <p style="margin-left: 133px;margin-top: 203px;position: absolute;">Make your selection count by liking Jam Audio.</p>
        </div>
    </div>
</div>


<% content_for :left_side do %>
    
    <div class="socialmedia" style="position:relative;">
        
        <a href="http://www.facebook.com/jamspeaker"><%= image_tag "transparent.gif", :class => "facebook" %></a>
        <a href="http://www.twitter.com/jamspeaker"><%= image_tag "transparent.gif", :class => "twitter" %></a>
        <a href="http://instagram.com/JamAudio"><%= image_tag "transparent.gif", :class => "instagram" %></a>
    </div>

    <% unless current_user %>
    <div class="sliderholder" style="position:relative">
        <%= image_tag "slidepick.png", :id => "viewcontrol", :style=>"position:relative" %>
    </div>

    <div style="width: 75px;height: 54px;background-color: transparent;position: relative;margin-right: 304px;float: right;margin-top: -63px;;cursor:pointer" onclick="ViewAll()"> </div>

    <% else %>
        <div style="margin-top: 167px;"></div>
    <% end %>


   

<% end %>

<% content_for :right_side do %>

    
<% end %>


<div id="scroller" class="centerofpage scrollable" style="top:239px;overflow:hidden;height:521px;width: 995px;">
    <div class="fltleft" style="overflow:hidden;margin-left:50px;height:700px">
        <p style="text-align:left;font-weight:bold;position:relative">
            <%= @firstvideo.name %>
        </p>
        <div class="videoframe bgcolororange shadowblue " style="position:relative">

            <div style="margin-left:20px;padding-top:20px" onmouseover="jwplayer('video_left').setMute(false);" onmouseout="jwplayer('video_left').setMute(true);">
                <div id="video_left"></div> 
            </div>

        </div>
        
        <div id="left_button_div" class="youpassbtn" onclick="formSubmit(<%= @firstvideo.id %>)"></div> 
    </div>
    <div class="fltright" style="margin-right:50px;">
        <p style="text-align:left;font-weight:bold">
            <%= @secondvideo.name %>
        </p>

        <div class="videoframe bgcolororange shadowpink" >

            <div style="margin-left:20px;padding-top:20px" onmouseover="jwplayer('video_right').setMute(false);" onmouseout="jwplayer('video_right').setMute(true);">
                <div id="video_right"></div> 
            </div>

        </div>

        <div id="right_button_div" class="youpassbtn" style="" onclick="formSubmit(<%= @secondvideo.id %>)"></div>   


    </div>


    </div>
    </div>




<img src="https://ad.amgdgt.com/ads/?t=ap&px=41949&rnd=<%= @timestamp%>" width="1" height="1" border="0"/>

<form id="whopass" accept-charset="UTF-8" action="/home/index" method="post" style="display:none">
    <input type="text" id="winner" name="winner" value="" />
</form>

<script>

    var test = '<%= current_user %>';
    var firstvideourl = '<%= @firstvideo.url %>';
    var secondvideourl = '<%= @secondvideo.url %>';
    var firstvideoimage = '<%= @firstvideo.thumbnail_image_url %>';
    var secondvideoimage = '<%= @secondvideo.thumbnail_image_url %>';

    $(document).ready(function() {

        $('.scrollable').perfectScrollbar();
        jwplayer("video_left").setup({
                file: firstvideourl,
                image: firstvideoimage,
                primary: "flash",
                width: 267,
                height: 267,
                autostart: false,
                repeat: true,
                mute: true,
            });

        

        jwplayer("video_right").setup({
                file: secondvideourl,
                image: secondvideoimage,
                primary: "flash",
                width: 267,
                height: 267,
                autostart: false,
                repeat: true,
                mute: true,
            });

        $("a.fancybox3").fancybox({ 
            afterClose: function() {
                jwplayer('video_left').play();
                jwplayer('video_right').play(); 

            }
        });


        $("a.fancybox2").fancybox({
        tpl: {
          closeBtn: '<div title="Close" id="fb_close_button"></div>'
         }
        });

        $( "#viewcontrol" ).draggable(
            { 
                axis: "x", 
                grid: [ 200, 0 ], 
                containment: "parent",
                stop: function() 
                {
                    var position = $('#viewcontrol').css('left');
                    
                    if (position == "100px")
                        location = "videos";
                }
            });

        $('#viewcontrol').css('left', '-100px');


    });




    if (!test)
    {
        $(document).ready(function() {
            document.getElementById('howtoenter').click();
        });
    }
    else
    {
        $(window).bind("load", function() {
            jwplayer('video_left').play();
            jwplayer('video_right').play(); 
        });
    }
        

    if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
        $('.socialmedia').css('margin-right', '254px');
    }

    
        

    
    

    

    function formSubmit(x)
    {
        if (test)
        {
            $('#winner').val(x);
            document.getElementById("whopass").submit();
        }
        else
        {
            document.getElementById('fbpopup_click').click();
        }
    }

    function ViewAll()
    {
        location = "videos";
    }





</script>

app/views/home/initvinevideos.html.erb
<% content_for :left_side do %>
<div style="text-align:left">
<%= simple_format(@text) %>
</div>
<% end %>

app/views/home/single.html.erb
<div class="centerofpage" style="width:400px;top:211px;">

	<div id="fbpopup" style="display:none">
		<div id="data" style="width:568px;height:346px">

	  		<%= image_tag "popupframe.png", :style => "position:absolute" %>

	  		<%= link_to("/auth/facebook", :id => "sign_in") do %>
		  		<%= image_tag "fblike.png", :style => "margin-left: 188px;margin-top: 100px;position:absolute" %>
			<% end %>

			
			<p style="margin-left: 106px;margin-top: 203px;position: absolute;">Make your selection count by liking Jam Audio.</p>
		</div>
	</div>

	<p style="text-align:left;font-weight:bold">
		<%= @video.name %>'s Videos
	</p>
	<div class="videoframe_big bgcolorgreen shadow" style="height: 418px;">
		<iframe width="350" height="350" src="<%= @video.url %>"></iframe>
	</div>

	
</div>
<div class="centerofpage" style="width:542px;top:681px;">
	<% if current_user %>
		<%= link_to("../") do %>
			<%= image_tag "gotodanceoff.png", :style => "margin-left: 0px;margin-top: 32px;float:left" %>
		<% end %>
		<%= link_to("/videos", :id => "sign_in") do %>
			<%= image_tag "viewallvideos.png", :style => "margin-left: 15px;margin-top: 32px;float:left" %>
		<% end %>
	<% else %>
		<a href="#data" class="fancybox" >
			<%= image_tag "supportmymoves.png", :style => "margin-left: 139px;margin-top: 34px;" %>
		</a>
	<% end %>

</div>
<div class="content bgcolor<%= @leftsidebgcolor %> fltleft">
	
	<% if current_user %>
	<div class="sliderholder" style="margin-top: 102px;">
		<%= image_tag "slidepick.png", :id => "viewcontrol" %>
	</div>
	<% end %>
</div>



<script>
	$(document).ready(function() {
		$("a.fancybox").fancybox();

		$("a.fancybox3").fancybox({ 
	  		closeBtn: false,
	  	});
	});

	$(function() {
    $( "#viewcontrol" ).draggable(
    	{ 
    		axis: "x", 
    		grid: [ 100, 0 ], 
    		containment: "parent",
    		stop: function() 
    		{
    			var position = $('#viewcontrol').css('left');
		        
		        if (position == "100px")
		        	location = "../videos";
		        if (position == "-100px")
		        	location = "../";
	      	}
    	});
});

</script>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Jam Dance Daddy Move Momma</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body style="background-color:white!important;font-family:arial!important">

			<%= yield %>

	</body>
</html>